### PR TITLE
Reanimated 2

### PR DESCRIPTION
**Pull request by Foosballfan**

### CODE REVIEW

**Comment by alexandrius** [comment]
Can you remove me from the repo?

**Comment by Foosballfan** [comment]
@alexandrius you probably need to unwatch the repo https://github.com/app-sapiens/classy-mall/watchers

**Comment by alexandrius** [comment]
I already unwatch you could remove me too

**Comment by Foosballfan** [comment]
Screenshot 2021-04-28 at 12 53 30

**Comment by Foosballfan** [comment]
@alexandrius looks like you are still watching. You have not been added to the repo, since it is public.

**Pull request merged**
