### PR TITLE
Improve animations and UI

### PR DESCRIPTION
**Pull request by alexandrius**

### CODE REVIEW

**Comment by Foosballfan** [comment]
Thanks for the PR Alex,

I'll put my feedback under separate headings.

**Code cleanliness**

- There are many cases where the formatting is inconsistent, e.g. spaces and number of lines. You can see this quite clearly with the newline in the app.js.
It's important that we always keep the code clean for consistency. Please install Prettier and make sure you format on save withing your ide.

- We do not leave commented out old code in the codebase for the same reasons as above. Please remove unused comments.

- Equally we don not want unused declarations and imports in the files. VS Code will highlight these as warnings, please follow the warnings.

**Header**

The new header you have created looks good, however the way that we render it entirely apart from react navigation causes weirdness, such as the header animating into the page on every page transition.  
Ideally we should be using a variant of your Header component but as part of react-native-navigation. Here is an example of how to add buttons into the header https://reactnavigation.org/docs/en/header-buttons.html

**Comment by alexandrius** [comment]
Ok I will review the notes and push another update. Won't log hours since
it shouldn't have happened at all.

**Comment by Foosballfan** [comment]
@alexandrius Finished with all the feedback now, was just saving periodically so github didn't lose all my text! 
Thanks

**Comment by Foosballfan** [comment]
Much better now, lets make this the starting quality for future reviews

**Comment by alexandrius** [comment]
@Foosballfan Sure thing!

**Pull request merged**
